
### Get all contacts
GET http://localhost:3000/contacts

### Get a single contact by ID
GET http://localhost:3000/contacts/69c36959c1d0a2af59bcc047

### Create a new contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
	"firstName": "annos",
	"lastName": "Doena",
	"email": "anny.doe@example.com",
	"favoriteColor": "purple",
	"birthday": "1999-02-05"
}

### Update a contact by ID
PUT http://localhost:3000/contacts/69c39814fcf3deae8d875bb8
Content-Type: application/json

{
	"firstName": "Janesa",
	"lastName": "Smith",
	"email": "jane.smith@example.com",
	"favoriteColor": "darkblue",
	"birthday": "1992-02-02"
}

### Delete a contact by ID
DELETE http://localhost:3000/contacts/69c371b4a878145c23ae5e5c
